blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ProductController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('products', 'ProductController');
Route::get('cart/checkout', 'CartController@checkout')->name('cart.checkout');
Route::resource('cart', 'CartController');
Route::resource('order', 'OrderController');

Route::get('/paysera/redirect/{id}', 'PayseraGatewayController@redirect')->name('paysera-redirect');
Route::get('/paysera/callback', 'PayseraGatewayController@callback')->name('paysera-callback');
Route::get('/paysera/uzsakymas-pavyko', 'PayseraGatewayController@success');
Route::get('/paysera/uzsakymas-nepavyko', function () {
    echo 'nepavyko';
});

blog/app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\User;
use Illuminate\Http\Request;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //session()->forget('cart');

        $products = User::cartItems();
        $cartTotal = User::cartValue();

        if(empty($products)){
            session()->flash('message', 'Your cart is empty');
            session()->flash('message-class', 'alert-danger');
        }

        //dd($products);
        return view('cart.index', [
            'products' => $products,
            'cartTotal' => $cartTotal,
        ]);
    }
    public function checkout(){

        return view('cart.checkout');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = Product::findOrFail(request('product_id'));

        $cart = session()->get('cart');

        if($cart == null){
            $cart = [];
        }


        if(array_key_exists($product->id, $cart)){
            $cart[$product->id]['quantity']++;
        } else {
            $cart[$product->id] = [
                'id' => $product->id,
                'title' => $product->title,
                'image' => $product->image,
                'price' => $product->price,
                'quantity' => 1
            ];
        }

        session()->put('cart', $cart);

        session()->flash('message', 'Your item was added');
        session()->flash('message-class', 'alert-success');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cart = session()->get('cart');
        if($request->has('number')){
            $cart[$id]['quantity'] = request('number');
        }
        //dd($cart);
        session()->put('cart', $cart);

        session()->flash('message', 'Successfully updated quantity of your item');
        session()->flash('message-class', 'alert-success');

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cart = session()->get('cart');
        unset($cart[$id]);
        session()->put('cart', $cart);

        session()->flash('message', 'Your item was removed');
        session()->flash('message-class', 'alert-danger');

        return redirect()->back();
    }
}

blog/resources/views/cart/checkout.blade.php
@extends('layouts.shop')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <form method="post" action="{{ route('order.store') }}">
                    @csrf
                    <label>Name</label>
                    <input class="form-control" type="text" name="full_name">
                    <label>email</label>
                    <input class="form-control" type="text" name="email">
                    <label> address</label>
                    <input class="form-control" type="text" name="delivery_address">
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>
@endsection

blog/resources/views/cart/index.blade.php
@extends('layouts.shop')
@section('content')
    <!-- cart-main-area start -->
    @if(isset($products))
    <div class="cart-main-area ptb--100 bg__white">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
{{--                    <form method="post" action="#">--}}
                        <div class="table-content table-responsive">
                            <table>
                                <thead>
                                <tr>
                                    <th class="product-thumbnail">products</th>
                                    <th class="product-name">name of products</th>
                                    <th class="product-price">Price</th>
                                    <th class="product-quantity">Quantity</th>
                                    <th class="product-subtotal">Total</th>
                                    <th class="product-remove">Remove</th>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach($products as $product)
                                    <tr>
                                        <td class="product-thumbnail">
                                            <a href="{{route('products.show', [$product->id])}}">
                                                <img src="{{ $product->image }}" alt="product img" />
                                            </a>
                                        </td>
                                        <td class="product-name"><a href="{{route('products.show', [$product->id])}}">{{$product->title}}</a>
                                            <ul  class="pro__prize">
                                                <li>${{$product->price}}</li>
                                            </ul>
                                        </td>
                                        <td class="product-price"><span class="amount">{{ $product->price * $product->quantity }}</span></td>
                                        <td class="product-quantity">

                                            <form method="post" action="{{route('cart.update', [$product->id])}}">
                                                @csrf
                                                @method('put')
                                                <input type="number" name="number" value="{{ $product->quantity }}" />
                                                <button class="action" type="submit">Up</button>
                                            </form>

                                        </td>
                                        <td class="product-subtotal">${{ $product->price * $product->quantity }}</td>
                                        <td class="product-remove">
                                            <form method="post" action="{{ route('cart.destroy', [$product->id]) }}">
                                                @csrf
                                                @method('delete')
                                                <button onclick="$(this).closest('form').submit()" class="action" type="submit" >
                                                    <i class="icon-trash icons"></i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="buttons-cart--inner">
                                    <div class="buttons-cart">
                                        <a href="{{ route('products.index') }}">Continue Shopping</a>
                                    </div>
                                    <div class="buttons-cart checkout--btn">

                                        <a href="#">update</a>
                                        <a href="{{ route('cart.checkout') }}">checkout</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <div class="ht__coupon__code">
                                    <span>enter your discount code</span>
                                    <div class="coupon__box">
                                        <input type="text" placeholder="">
                                        <div class="ht__cp__btn">
                                            <a href="#">enter</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12 col-xs-12 smt-40 xmt-40">
                                <div class="htc__cart__total">
                                    <h6>cart total</h6>
                                    <div class="cart__desk__list">
                                        <ul class="cart__desc">
                                            <li>cart total</li>
                                            <li>shipping</li>
                                        </ul>
                                        <ul class="cart__price">
                                            <li>${{ $cartTotal }}</li>
                                            <li>0</li>
                                        </ul>
                                    </div>
                                    <div class="cart__total">
                                        <span>order total</span>
                                        <span>${{ $cartTotal }}</span>
                                    </div>
                                    <ul class="payment__btn">
                                        <li class="active"><a href="#">payment</a></li>
                                        <li><a href="{{ route('products.index') }}">continue shopping</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
{{--                    </form>--}}
                </div>
            </div>
        </div>
    </div>
    @endif
    <!-- cart-main-area end -->
@endsection